# Robot Configuration Parameters
TrajectoryPlannerROS:
    acc_lim_x: 1.25
    acc_lim_y: 1.25
    acc_lim_th: 1.6
    max_vel_x: 0.5
    min_vel_x: 0.1
    max_rotational_vel: 1.2
    min_in_place_rotational_vel: 0.1
    escape_vel: -0.1
    holonomic_robot: true
    y_vels: [-0.5, -0.1, 0.1, 0.5]

    # Goal Tolerance Parameters
    xy_goal_tolerance: 0.1
    yaw_goal_tolerance: 0.1

    # Forward Simulation Parameters
    sim_time: 1.7
    sim_granularity: 0.025
    vx_samples: 3
    vtheta_samples: 6

    # Trajectory Scoring Parameters
    goal_distance_bias: 0.8
    path_distance_bias: 5.0
    occdist_scale: 0.01
    heading_lookahead: 0.5
    dwa: true

    # Oscillation Prevention Parameters
    oscillation_reset_dist: 0.40

DWAPlannerROS:
  acc_lim_th: 1.5
  acc_lim_x: 1.5
  acc_lim_y: 1.5

  dec_lim_th: 4.5
  dec_lim_x: 2.5
  dec_lim_y: 2.5

  max_vel_x: 0.6
  min_vel_x: -0.6

  max_vel_y: 0.3
  min_vel_y: -0.3

  max_trans_vel: 0.6
  min_trans_vel: 0.1

  max_rot_vel: 0.75
  min_rot_vel: 0.2

  sim_time: 1.7
  sim_granularity: 0.025

  goal_distance_bias: 32.0
  path_distance_bias: 0.4

  heading_bias: 24.0

  squared_dist_for_rotating: 1

  occdist_scale: 0.01

  stop_time_buffer: 0.2
  oscillation_reset_dist: 0.2

  forward_point_distance: 0.325 #0.325 Do not enforce moving forwards

  scaling_speed: 0.35
  max_scaling_factor: 0.1

  vx_samples: 9
  vy_samples: 9
  vth_samples: 5

  sim_period: 0.2

  xy_goal_tolerance: 0.075
  yaw_goal_tolerance: 0.05

  rot_stopped_vel: 0.01
  trans_stopped_vel: 0.01

  penalize_negative_x: false
  prune_plan: true

  publish_cost_grid_pc: true

NavfnROS:
  default_tolerance: 0.2
  visualize_potential: true
  allow_unknown: false

EBandPlannerROS:
  #Set the acceleration limits of the robot
  max_acceleration: 0.5
  virtual_mass: 0.75
  max_translational_acceleration: 0.5
  max_rotational_acceleration: 1.5

  #Set the velocity limits of the robot
  max_vel_lin: 0.6
  max_vel_th: 0.8
  min_vel_lin: 0.1
  min_vel_th: 0.0
  min_in_place_vel_th: 0.0
  in_place_trans_vel: 0.0

  rotation_correction_threshold: 0.2
